"""models updated

Revision ID: 8d91b675e7f9
Revises: a8372a82f969
Create Date: 2023-03-07 20:43:51.769559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d91b675e7f9"
down_revision = "a8372a82f969"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pipeline_id", sa.Integer(), nullable=False),
        sa.Column("in_data", sa.String(), nullable=False),
        sa.Column("top_left_x", sa.Integer(), nullable=True),
        sa.Column("top_left_y", sa.Integer(), nullable=True),
        sa.Column("w", sa.Integer(), nullable=True),
        sa.Column("h", sa.Integer(), nullable=True),
        sa.Column("conf", sa.Float(), nullable=False),
        sa.Column("label", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipeline.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("pipeline_stage", sa.Column("order", sa.Integer(), nullable=False))
    op.drop_constraint("pipeline_stage_stage_id_fkey", "pipeline_stage", type_="foreignkey")
    op.drop_constraint("pipeline_stage_pipeline_id_fkey", "pipeline_stage", type_="foreignkey")
    op.create_foreign_key(
        None, "pipeline_stage", "pipeline", ["pipeline_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "pipeline_stage", "stage", ["stage_id"], ["id"], ondelete="CASCADE")
    op.add_column("stage", sa.Column("meth_name", sa.String(), nullable=False))
    op.add_column("stage", sa.Column("args", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stage", "args")
    op.drop_column("stage", "meth_name")
    op.drop_constraint(None, "pipeline_stage", type_="foreignkey")
    op.drop_constraint(None, "pipeline_stage", type_="foreignkey")
    op.create_foreign_key(
        "pipeline_stage_pipeline_id_fkey", "pipeline_stage", "pipeline", ["pipeline_id"], ["id"]
    )
    op.create_foreign_key(
        "pipeline_stage_stage_id_fkey", "pipeline_stage", "stage", ["stage_id"], ["id"]
    )
    op.drop_column("pipeline_stage", "order")
    op.drop_table("sample")
    # ### end Alembic commands ###
