services:
  db:
    image: postgres:14.3-alpine
    restart: on-failure
    volumes:
      - ../.database:/var/lib/postgresql/data/
    env_file: .env

  image_processor:
    image: image_processor
    env_file: .env
    restart: always
    ports:
      - "8080:8080"

  detector:
    image: detector
    env_file: .env
    restart: always
